CPP = g++
CPPFLAGS = -Wall -Wextra

all: 
	cd ./AArray ; $(MAKE)
	cd ./VArray ; $(MAKE)
	cd ./SArray ; $(MAKE)

clean:
	cd ./AArray ; $(MAKE) clean
	cd ./VArray ; $(MAKE) clean
	cd ./SArray ; $(MAKE) clean
